{10514}{10606} Allen, Bomb Squad, Special Services...
{10608}{10748} State Police and the FBI!
{10750}{10926} Lieutenant! I want you to go to St. John's Emergency...
{10928}{11074} in case we got any walk-ins from the street.
{11076}{11188} Kramer, get the city engineer!
{11190}{11284} I gotta find out a damage report. It's very important.
{11342}{11438} Who the hell would want to blow up a department store?
